site_name: "veTurboIO"

theme:
  name: "material"

docs_dir: docs

nav: 
  - 首页: index.md
  - 最佳实践:
    - 动态加载: dynamic_load.md
    - SFCS 加载优化: sfcs_support.md
  - API: api.md
  - 发布日志: release.md

plugins:
- mkdocstrings:
    default_handler: python