
[tool.isort]
profile = "black"  # black-compatible
line_length = 119  # should match black parameters
py_version = 310  # python 3.10 as a target version
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"


[tool.black]
line_length = 119
skip_string_normalization = true
