MLP_SECRET_KEY_FILENAME = "MLP_SECRET_KEY"
MLP_ACCESS_KEY_FILENAME = "MLP_ACCESS_KEY"

SFCS_DEFAULT_CONFIG_PATH_ENV = "SFCS_METAINFO_PATH"

SFCS_DEFAULT_METAINFO_PATH = "/root/.volc/SFCSConfiguration.json"

RDMA_NIC_ENV = "MLP_RDMA_NIC_NAMES"
DEFAULT_NIC_NAME = "eth0"
RDMA_SEGMENT_ENV = "MLP_RDMA_NETWORK_SEGMENT"
DEFAULT_CREDENTIAL_PATH_ENV = "CREDENTIAL_PATH"
DEFAULT_CREDENTIAL_PATH = "/mlplatform/.credential/"
